language: node_js
node_js: stable
script:
- npm run test:lint:js
- npm run test:lint:wc
- polymer test --skip-plugin local
addons:
  sauce_connect: true
  jwt:
    secure: Y/9Wuw/Y1PJCXJgjlbFphHgzeSVRJ8s7I+eGyhf/oRAzWMpMQV46fSUQXP8u8bkC40/T9tw0eM0/1ue08P7QV1Dnm0N18W3n9vMr9XRMFzXCor9RLnNfiMY43AQL0fLNaXsR+MBDHVMIJ86RYgDwTGajvF+3Pb1E+bm8oYdNkeELo2Ko3pPx7SMeTx3Kc8i41f4FzAVtm++g6ot6KksAGLXNKt3pM2jpzZ0cbxS3wEpgobZrHy+8p9LZfRX5WYEtvhN1K8aA0W8mZWaSwBSpatGLOGkeySRjtjSTX7AMOxaLzfsfliL7GAyZFWnHH2OPQ5Guv3tI+GRjmNrTUN9lLcC4MJ3C9jo+x49yypbUwx2tNNd3J1bs6skHQwR86r5hHGlUm/Fq2h0Ms2zkAJqe7WGvM+nSHiEDghe1y9BTy5CkUkVH1vZWOm3c+1szsxF4UE9SiwxjlsA8HjTJWJmgFTypMoKU+KZ4HxUyVKcIGLlYlRK7UsBfSL19ASBu2HsJS4H4HUB5TmvHet3eOnERkamy7yMdJ97KR0ruqxXRalISwhTfm2Ropf5doW+sy5mGKtLorUdrwfCH7+4MN/3k4pAEsM7M8MvkGh8pQE2CqVunfVs9k1zUiYhmNT2oNUsDIznUmSC+LwGQN0xwhby7uFuDOkkTF/LhIkkS6Qvtorw=
env:
  global:
    SAUCE_USERNAME: Desire2Learn
