language: node_js
node_js: stable
script:
- npm run test:lint
- wct --skip-plugin local
addons:
  sauce_connect: true
  jwt:
    # SAUCE_ACCESS_KEY
    secure: X5a3WMplCqOIOINZ2hqFHj8zvrwH46DmTLitubRMwb3q/87agbRCwkyvwOaETj1pgyB8ZGTkVlgHOfiAuKDKd7mgadsejw1yDIO7s4zjXv+Yi2hEQwSf1yNejJYnXkvti26/IPEvwZDpxgcBE0x0gPqb0a6bbQ9haolwvDcjc7zVGu7EneultXzGYuiB1M7wLxN0qHtPdrPQ7eO1RSqgXIbCdjIJcO51PfBwgC78rvCYB7Cikvq4kCqyA1Lc2vRytMsyD6sUqLPKDYgvTMI41wFlMDpAL3SPIay0sehprF5G2gX/xQ+3zT8bOn/KPEMwskOGcvvkarDRRGdb2aS4x7nzCayBOocvOjjdQR3cU1hyV4D2jfad/RAMIK9eezQYJu2445A8TbXMK8RCqrqgCKRgB+4VYgalV9WoB7qAjHPuhxdSgG8eulbG0RvZBY+4PtV1ILWs0MzUdEuo5VHcEp20qL+aZe3bbQYiUJD5rXkcInDun3zlslGHxFGsieM9RCLSwzwg4Apkj52fNLkh0euxgB8sLpxZe3TmCRF5NTwscqKASpehAW4VqzgyGuXXR+8Xf6WTh1eK+t3PRRwVjhTR4jYB1JR9u34UHkmhBisCloBTnbff/hzIqbPl6SdJqZj7IOG5s7p2Xav5SqL/EGadkn8bMvBXZkDnT/6vTto=
env:
  global:
    # SAUCE_USERNAME
    secure: ts2MM/upTrS/6okrVVDYVW8txEIwbUqW6ohFordeLxbdjlPNjG3sImWEzIkaOeR2v8obxUVzJ4sb2h2NeRalVC3f1JrqY8riHQM0EfdTYlZn9gzUgO/7D5qWe9So50CAOmnRxXMk5ofjVyXmcfgmYHD6laQeq9bq3VWAzWNgYKZ/IjBDsEgVq8F2xZBO8U6EkHs82okfsomsmW2w3wRlKsrbVuCFxoJdCpOw0w43sxN7WVFyAm/vYxp/OiV4mJRFJGPf6GHg9meY42z8Nd+rcHGUmSZba3zPModuiAiXcE9hI8gSol0KkTsT/ll8r7rHmUzSlQGCmn5dHF4zDEr16oUHFuyDDxNGZH0tUDNUE6GaFJCqDLZzwLBhM8dZ9YiVILmcj/IdRqw7yiWm1BlAgzwVInJNnQ6daU4O5yzL/aoxaPWS9afsYC/u5ykP7ryiBXfMtEvKtKqIDR+c10R+P9HKvmKFMfP3nJ7N836fa0b8VNJhblgIiyczVhVS2zc/zsssVtpIGlgzHS7q+4/SIuKu+Sd/+2FB2LkkZfOr9qbT7ds8dyPc8DrA5BCzKjeWqS4jLafp2QURveoeDfxOEQvjc/dXMAy/EWx4bVGeD3+uPNAaBJ5Aai2M16rIu7CBVL0/SJ90hIoCX9IU/kLD/dA1WqT4DoWxrSTDutUNZp8=
